PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MAMAN: Bon…\p"
    .string "Tous les garçons quittent\n"
    .string "un jour la maison. C'est la vie!\p"
    .string "Le PROF. CHEN te cherche. Il est\n"
    .string "dans la maison voisine.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MAMAN: Bon…\p"
    .string "Il paraît que c'est le rêve de\n"
    .string "toutes les filles de voyager.\p"
    .string "Le PROF. CHEN te cherche. Il est\n"
    .string "dans la maison voisine.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Il y a un film à la télé.\p"
    .string "Y'a un gars cool dans un taxi.\p"
    .string "Bon…\n"
    .string "Je ferais bien d'y aller.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Il y a un film à la télé.\p"
    .string "C'est le Seigneur des Agneaux.\p"
    .string "Bon…\n"
    .string "Je ferais bien d'y aller.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

